### ISSUE TITLE
Right nav

### ISSUE THREAD

**Issue by amol-anand** [hlxsites/channelco-iot#5]
![image](https://github.com/hlxsites/channelco-iot/assets/7074782/37811f85-ce21-4cea-9b52-b065ce2bc514)

Auto blocked on all pages by default

Will always include the following content:
- Brightcove video player
- Ad
- Podcast playlist (external include)
- Twitter

**Comment by ravkiran** [comment]
Except the `Ad`, everything else is implemented by https://github.com/hlxsites/channelco-iot/pull/17, https://github.com/hlxsites/channelco-iot/pull/18

**Comment by ravkiran** [comment]
`Ad` will be done in #28, so closing this issue.
